# Mock traceroutes to inject into backend code for testing
import pandas as pd

columns = [
            '__name__',
            'host',
            'instance',
            'job',
            'name',
            'path',
            'target',
            'ttl',
            'type'
        ]
mock_tracert_df_1 = pd.DataFrame(
    [
        [
            'mtr_rtt_seconds',
            'localhost',
            'localhost:9427',
            'network_exporter',
            'google-dns', 
            '172.17.0.1', 
            '1.1.1.1', 
            '1',
            'mean'
        ],
        [
            'mtr_rtt_seconds',
            'localhost',
            'localhost:9427',
            'network_exporter',
            'google-dns', 
            '192.168.1.254', 
            '1.1.1.1', 
            '2',
            'mean'
        ],
        [
            'mtr_rtt_seconds',
            'localhost',
            'localhost:9427',
            'network_exporter',
            'google-dns', 
            '10.56.8.1', 
            '1.1.1.1', 
            '3',
            'mean'
        ],
        [
            'mtr_rtt_seconds',
            'localhost',
            'localhost:9427',
            'network_exporter',
            'google-dns', 
            '154.11.15.105', 
            '1.1.1.1', 
            '4',
            'mean'
        ],
        [
            'mtr_rtt_seconds',
            'localhost',
            'localhost:9427',
            'network_exporter',
            'google-dns', 
            '154.11.16.73', 
            '1.1.1.1', 
            '5',
            'mean'
        ],
        [
            'mtr_rtt_seconds',
            'localhost',
            'localhost:9427',
            'network_exporter',
            'google-dns', 
            '1.1.1.1', 
            '1.1.1.1', 
            '6',
            'mean'
        ],
    ],
    columns=columns,
    index=[1643814767.308,1643814767.308,1643814767.308,1643814767.308,1643814767.308,1643814767.308]
)
mock_tracert_df_2 = pd.DataFrame(
    [
        [
            'mtr_rtt_seconds',
            'localhost',
            'localhost:9427',
            'network_exporter',
            'google-dns', 
            '172.17.0.1', 
            '1.1.1.1', 
            '1',
            'mean'
        ],
        [
            'mtr_rtt_seconds',
            'localhost',
            'localhost:9427',
            'network_exporter',
            'google-dns', 
            '192.138.1.123', 
            '1.1.1.1', 
            '2',
            'mean'
        ],
        [
            'mtr_rtt_seconds',
            'localhost',
            'localhost:9427',
            'network_exporter',
            'google-dns', 
            '10.31.8.1', 
            '1.1.1.1', 
            '3',
            'mean'
        ],
        [
            'mtr_rtt_seconds',
            'localhost',
            'localhost:9427',
            'network_exporter',
            'google-dns', 
            '15.50.60.111', 
            '1.1.1.1', 
            '4',
            'mean'
        ],
        [
            'mtr_rtt_seconds',
            'localhost',
            'localhost:9427',
            'network_exporter',
            'google-dns', 
            '154.11.16.73', 
            '1.1.1.1', 
            '5',
            'mean'
        ],
        [
            'mtr_rtt_seconds',
            'localhost',
            'localhost:9427',
            'network_exporter',
            'google-dns', 
            '1.1.1.1', 
            '1.1.1.1', 
            '6',
            'mean'
        ],
    ],
    columns=columns,
    index=[1643814764.308,1643814764.308,1643814764.308,1643814764.308,1643814764.308,1643814764.308]
)